name: Testing Coverage
on: [push, pull_request]
jobs:
  build:
    name: Test and Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.18.0"

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare coverage
        run: mkdir coverage

      - name: Test
        run: go test ./... -coverprofile coverage/coverage.out

      - name: Coverage convert
        uses: jandelgado/gcov2lcov-action@v1.0.8
        with:
          infile: coverage/coverage.out
          outfile: coverage/lcov.info

      - name: Coveralls report
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
